// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNqiMYxzso2LbBYXRlEyMYVIKH5iN69oM',
    appId: '1:289965211734:web:a59bc18c9061dbf6257bf7',
    messagingSenderId: '289965211734',
    projectId: 'ecommerce-app-17dd2',
    authDomain: 'ecommerce-app-17dd2.firebaseapp.com',
    storageBucket: 'ecommerce-app-17dd2.firebasestorage.app',
    measurementId: 'G-4KT3TV551H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_M3UqqIX_IJEmilw7EhoIkzUsTpgO91Y',
    appId: '1:289965211734:android:f59da269aeae538b257bf7',
    messagingSenderId: '289965211734',
    projectId: 'ecommerce-app-17dd2',
    storageBucket: 'ecommerce-app-17dd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPrffetR1rZQXQvePNr-w9RRMxyyJycKg',
    appId: '1:289965211734:ios:cbf57ef6396707f4257bf7',
    messagingSenderId: '289965211734',
    projectId: 'ecommerce-app-17dd2',
    storageBucket: 'ecommerce-app-17dd2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPrffetR1rZQXQvePNr-w9RRMxyyJycKg',
    appId: '1:289965211734:ios:cbf57ef6396707f4257bf7',
    messagingSenderId: '289965211734',
    projectId: 'ecommerce-app-17dd2',
    storageBucket: 'ecommerce-app-17dd2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNqiMYxzso2LbBYXRlEyMYVIKH5iN69oM',
    appId: '1:289965211734:web:70ff952d4d8cbd74257bf7',
    messagingSenderId: '289965211734',
    projectId: 'ecommerce-app-17dd2',
    authDomain: 'ecommerce-app-17dd2.firebaseapp.com',
    storageBucket: 'ecommerce-app-17dd2.firebasestorage.app',
    measurementId: 'G-RF9Q03SLJ1',
  );
}
